import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"",ENV_ANON_KEY=Deno.env.get("SUPABASE_ANON_KEY")||"",PUBLIC_MARKER="moreno-public-v23",V9=`${SUPABASE_URL}/functions/v1/ai-moreno-investigator-v9`,V8=`${SUPABASE_URL}/functions/v1/ai-moreno-investigator-v8`;
const ALLOWED_ORIGINS=new Set(["https://mysterylogic.com","https://www.mysterylogic.com","https://valera2872.github.io","https://rawcdn.githack.com"]);
function clean(v:unknown,max=1200){return typeof v==="string"?v.replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,max):""}
function qnorm(v:unknown){return clean(v,1200).toLowerCase().replace(/ё/g,"е").replace(/[.,!?;:()«»"']/g," ").replace(/\s+/g," ").trim()}
function cors(origin:string){return {"access-control-allow-origin":origin||"https://mysterylogic.com","access-control-allow-headers":"content-type, x-ml-client-version","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","vary":"Origin"}}
function clientAuthorized(req:Request){return (req.headers.get("x-ml-client-version")||"")===PUBLIC_MARKER}
function upstreamHeaders(){return {authorization:`Bearer ${ENV_ANON_KEY}`,apikey:ENV_ANON_KEY,"content-type":"application/json",origin:"https://mysterylogic.com","x-ml-client-version":PUBLIC_MARKER}}
function finalSubmission(body:any){if(clean(body?.action,30)!=="plan")return null;const command=clean(body?.command,3000);if(!/^передаю итоговую реконструкцию\./i.test(command))return null;const hypothesis=command.replace(/^передаю итоговую реконструкцию\.\s*/i,"").trim();if(!hypothesis)return null;return {operations:[{op:"record_hypothesis",hypothesis},{op:"submit_case"}],mode:"player_final_reconstruction",player_led:true,automatic_solution_inference:false,automatic_evidence_ranking:false}}
function ambiguousEvidenceIdentity(body:any){if(clean(body?.action,30)!=="plan")return false;const q=qnorm(body?.command);if(!q)return false;const summon=/(?:выз[а-я]*|позов[а-я]*|приглас[а-я]*|допрос[а-я]*|опрос[а-я]*|привед[а-я]*|достав[а-я]*|дай[а-я]*\s+поговор[а-я]*|хочу\s+поговор[а-я]*)/.test(q);if(!summon)return false;return /(?:убийц[а-я]*|стрелок[а-я]*|того\s+кто\s+стрел[а-я]*|тот\s+кто\s+стрел[а-я]*)/.test(q)||/мужчин[а-я]*[^.]{0,80}(?:над\s+(?:patricia|патриц[а-я]*)|стоя[а-я]*\s+над)/.test(q)||/(?:над\s+(?:patricia|патриц[а-я]*))[^.]{0,80}мужчин[а-я]*/.test(q)}
function retryable(status:number){return status===401||status===403||status===500||status===502||status===503||status===504}
async function call(url:string,body:any){return fetch(url,{method:"POST",headers:upstreamHeaders(),body:JSON.stringify(body)})}
Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin")||"";if(origin&&!ALLOWED_ORIGINS.has(origin))return new Response(JSON.stringify({error:"origin_not_allowed"}),{status:403,headers:{"content-type":"application/json"}});const headers=cors(origin||"https://mysterylogic.com"),json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers});if(req.method==="OPTIONS")return new Response("ok",{headers});if(!clientAuthorized(req))return json({error:"unauthorized_client"},401);if(req.method!=="POST")return json({error:"method_not_allowed"},405);if(!ENV_ANON_KEY)return json({error:"upstream_public_key_missing"},503);let body:any;try{body=await req.json()}catch{return json({error:"invalid_json"},400)}if(clean(body?.action,30)==="status")return json({version:11,upstream_primary:"ai-moreno-investigator-v9",upstream_fallback:"ai-moreno-investigator-v8",final_reconstruction:true,player_leads_investigation:true});const final=finalSubmission(body);if(final)return json(final);if(ambiguousEvidenceIdentity(body))return json({operations:[{op:"clarify",note:"Уточните, кого именно из уже установленных людей вы хотите вызвать или допросить. Описание из материалов дела само по себе не устанавливает личность."}],mode:"identity_inference_guardrail",player_led:true,automatic_identity_inference:false,automatic_contradiction_detection:false});try{const primary=await call(V9,body),text=await primary.text();if(!retryable(primary.status))return new Response(text,{status:primary.status,headers});console.error("moreno_v11_primary_failed",primary.status,clean(text,300))}catch(error){console.error("moreno_v11_primary_exception",String(error))}try{const fallback=await call(V8,body),text=await fallback.text();return new Response(text,{status:fallback.status,headers})}catch(error){console.error("moreno_v11_fallback_exception",String(error));return json({error:"ai_gateway_unavailable",message:"ИИ-маршрут временно недоступен. Попробуйте ещё раз."},502)}});