'use strict';
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const catalog=JSON.parse(fs.readFileSync(path.join(root,'assets/generated/cases-index.json'),'utf8'));
const html=fs.readFileSync(path.join(root,'dela/index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'assets/catalog-experience.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/catalog-experience.css'),'utf8');

assert.equal(catalog.totalCases,100);
assert.equal(catalog.freeCount,15);
assert.equal(catalog.premiumCount,85);
assert.equal((html.match(/class="case-card /g)||[]).length,100,'catalog must render 100 case cards');
assert.equal((html.match(/data-access="free"/g)||[]).length,15,'catalog must render 15 free cards');
assert.equal((html.match(/data-access="premium"/g)||[]).length,85,'catalog must render 85 premium cards');
assert.ok(html.includes('data-catalog-progress'),'command center is missing');
assert.ok(html.includes('data-catalog-continue'),'continue action is missing');
assert.ok(html.includes('data-catalog-random'),'random free case action is missing');
assert.ok(html.includes('id="case-difficulty"'),'difficulty filter is missing');
assert.ok(html.includes('id="case-category"'),'category filter is missing');
assert.ok(html.includes('id="case-unsolved"'),'unsolved-only filter is missing');
assert.ok(html.includes('catalog-experience.css?v=1.6.0'),'catalog 1.6 stylesheet is not versioned');
assert.ok(html.includes('catalog-experience.js?v=1.6.0'),'catalog 1.6 script is not versioned');
assert.ok(!html.includes('full-catalog.js?v='),'legacy filter script must not compete with catalog 1.6');
assert.ok(js.includes('MysteryLogicDossier'),'catalog must read dossier progress');
assert.ok(js.includes("data.progress=solved?'solved':active?'active':'new'"),'case progress states are missing');
assert.ok(js.includes('pickRandomCase'),'random unsolved selection is missing');
assert.ok(js.includes("injectedProgress?.remove()"),'old duplicate progress panel is not suppressed');
assert.ok(css.includes('.catalog-command'),'command center styling is missing');
assert.ok(css.includes('.case-card.is-solved'),'solved case styling is missing');
assert.ok(css.includes('.case-card.is-active-case'),'active case styling is missing');

console.log('catalog experience 1.6 tests passed: 100 total / 15 free / 85 locked');
