'use strict';
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const catalog=JSON.parse(fs.readFileSync(path.join(root,'assets/generated/cases-index.json'),'utf8'));
assert.equal(catalog.totalCases,100);
assert.equal(catalog.freeCount,15);
assert.equal(catalog.premiumCount,85);
assert.equal(catalog.cases.length,100);
assert.equal(catalog.freeCases.length,15);
assert.equal(new Set(catalog.cases.map(item=>item.id)).size,100);
assert.equal(new Set(catalog.cases.map(item=>item.path)).size,100);
global.KtoVretCatalog=catalog;
delete require.cache[require.resolve('../assets/dossier-model.js')];
const model=require('../assets/dossier-model.js');
assert.equal(model.cases.length,15);
const empty={getItem:()=>null,removeItem:()=>undefined};
assert.equal(model.summarize(model.readRecords(empty)).totalCases,15);
for(const item of catalog.freeCases)assert.ok(fs.existsSync(path.join(root,item.path,'index.html')),`missing free page ${item.path}`);
for(const item of catalog.cases.filter(entry=>entry.access==='premium')){const html=fs.readFileSync(path.join(root,item.path,'index.html'),'utf8');assert.ok(!html.includes('window.KtoVretWeb='),`premium case leaked into ${item.path}`);}
console.log('generated library tests passed: 100 total, 15 free, 85 locked');
