import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const V4=`${SUPABASE_URL}/functions/v1/ai-moreno-investigator-v4`;
const ALLOWED_ORIGINS=new Set(["https://mysterylogic.com","https://www.mysterylogic.com","https://valera2872.github.io","https://rawcdn.githack.com"]);
const TARGETS=new Set(["boyfriend","mother","older_daughter","younger_daughter","second_floor_witness"]);

type MemoryEntry={entry_id:string;turn:number;actor_id:string;actor:string;type:"statement"|"confrontation";command:string;title:string;body:string};
type Mention={id:string;index:number;end:number};

function clean(v:unknown,max=1400){return typeof v==="string"?v.replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,max):""}
function qnorm(s:string){return s.toLowerCase().replace(/ё/g,"е").replace(/[.,!?;:()«»\"']/g," ").replace(/\s+/g," ").trim()}
function cors(origin:string){return {"access-control-allow-origin":origin||"https://mysterylogic.com","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","vary":"Origin"}}
function doneSet(v:unknown){return new Set(Array.isArray(v)?v.map(x=>clean(x,50)).filter(Boolean):[])}
function knownTargets(done:Set<string>){const s=new Set<string>();if(done.has("people")){s.add("boyfriend");s.add("mother");s.add("older_daughter");s.add("younger_daughter")}if(done.has("witnessLocated"))s.add("second_floor_witness");return s}
function targetName(id:string){return ({boyfriend:"бойфренд старшей дочери",mother:"приёмная мать Patricia",older_daughter:"старшая дочь приёмной матери",younger_daughter:"младшая дочь приёмной матери",second_floor_witness:"бывший житель второго этажа"} as Record<string,string>)[id]||id}
function memoryEntries(v:unknown){if(!v||typeof v!=="object")return[] as MemoryEntry[];const a=(v as any).entries;if(!Array.isArray(a))return[] as MemoryEntry[];return a.slice(-40).map((e:any,i:number)=>({entry_id:clean(e?.entry_id,50)||`legacy-${Number(e?.turn)||0}-${i+1}`,turn:Number(e?.turn)||0,actor_id:clean(e?.actor_id,40),actor:clean(e?.actor,90),type:e?.type==="confrontation"?"confrontation":"statement",command:clean(e?.command,260),title:clean(e?.title,180),body:clean(e?.body,1200)})).filter((e:MemoryEntry)=>e.actor_id&&e.body)}
function mentions(q:string){const defs:[string,RegExp][]=[
 ["boyfriend",/бойфренд|парн\w*\s+доч/g],
 ["mother",/приемн\w*\s+мат|матер\w*/g],
 ["older_daughter",/старш\w*\s+доч/g],
 ["younger_daughter",/младш\w*\s+доч/g],
 ["second_floor_witness",/сосед\w*|жител\w*\s+втор|свидетел\w*\s+втор/g]
 ];const out:Mention[]=[];for(const [id,re] of defs){re.lastIndex=0;for(const m of q.matchAll(re))out.push({id,index:m.index||0,end:(m.index||0)+m[0].length})}return out.sort((a,b)=>a.index-b.index||a.end-b.end)}
function statementNounAt(q:string){const m=q.match(/показан\w*|слов\w*|ответ\w*|верси\w*/);return m?{index:m.index||0,end:(m.index||0)+m[0].length}:null}
function isManualPresentation(q:string){const noun=statementNounAt(q);if(!noun||!/предъяв\w*|покаж\w*|зачит\w*|ознаком\w*/.test(q))return false;return mentions(q).some(m=>m.index>=noun.end)}
function sourceAndTarget(q:string,focus:string){const noun=statementNounAt(q);if(!noun)return{source:"",target:""};const ms=mentions(q),after=ms.filter(m=>m.index>=noun.end);if(!after.length)return{source:"",target:""};const sourceMention=after[0],source=sourceMention.id;const before=ms.filter(m=>m.end<=noun.index&&m.id!==source);const otherAfter=after.filter(m=>m!==sourceMention&&m.id!==source);const explicitTarget=(before.length?before[before.length-1]?.id:"")||(otherAfter.length?otherAfter[0]?.id:"");return{source,target:explicitTarget||focus}}
function ordinal(q:string){if(/(?:^|\s)(?:последн\w*)(?:\s|$)/.test(q))return-1;if(/(?:^|\s)(?:перв\w*|1)(?:\s|$)/.test(q))return1;if(/(?:^|\s)(?:втор\w*|2)(?:\s|$)/.test(q))return2;if(/(?:^|\s)(?:трет\w*|3)(?:\s|$)/.test(q))return3;if(/(?:^|\s)(?:четверт\w*|4)(?:\s|$)/.test(q))return4;return0}
const STOP=new Set(["предъяв","покажи","показан","зачитай","ознаком","слова","словами","ответ","версия","версии","бойфренд","старшей","дочери","приемная","приёмная","матери","младшая","старшая","соседа","сосед","жителя","второго","этажа","свидетеля","этому","ему","ей","его","ее","её","мне","что","который","которые","первое","второе","третье","последнее"]);
function stems(s:string){return [...new Set(qnorm(s).split(/\s+/).filter(x=>x.length>=5&&!STOP.has(x)).map(x=>x.slice(0,5)))]}
function selectStatement(q:string,rows:MemoryEntry[]){if(rows.length===1)return rows[0];const n=ordinal(q);if(n===-1)return rows[rows.length-1];if(n>0&&n<=rows.length)return rows[n-1];const qs=new Set(stems(q));let best:MemoryEntry|null=null,bestScore=0,tied=false;for(const row of rows){const score=stems(row.body).filter(x=>qs.has(x)).length;if(score>bestScore){best=row;bestScore=score;tied=false}else if(score===bestScore&&score>0)tied=true}return bestScore>0&&!tied?best:null}
function options(rows:MemoryEntry[]){return rows.slice(0,6).map((e,i)=>`${i+1}) ${e.body.slice(0,220)}${e.body.length>220?"…":""}`).join(" ")}
async function forward(req:Request,body:any,headers:Record<string,string>){const auth=req.headers.get("authorization")||"",apikey=req.headers.get("apikey")||"";const r=await fetch(V4,{method:"POST",headers:{authorization:auth,apikey,"content-type":"application/json","origin":req.headers.get("origin")||"https://mysterylogic.com"},body:JSON.stringify(body)});const text=await r.text();return new Response(text,{status:r.status,headers})}

Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin")||"";if(origin&&!ALLOWED_ORIGINS.has(origin))return new Response(JSON.stringify({error:"origin_not_allowed"}),{status:403,headers:{"content-type":"application/json"}});const headers=cors(origin||"https://mysterylogic.com");const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers});if(req.method==="OPTIONS")return new Response("ok",{headers});if(req.method!=="POST")return json({error:"method_not_allowed"},405);let body:any;try{body=await req.json()}catch{return json({error:"invalid_json"},400)};const action=clean(body.action,30),done=doneSet(body.completed),entries=memoryEntries(body.memory),known=knownTargets(done);
 if(action==="status")return json({version:5,planner_policy:"compound-v2+source-grounded-confrontation+retrieval-only-memory+manual-statement-confrontation",upstream:"ai-moreno-investigator-v4",player_leads_investigation:true,automatic_contradiction_detection:false});
 if(action==="plan"){const q=qnorm(clean(body.command,900));if(isManualPresentation(q)){const focus=clean(body.focus,40),pick=sourceAndTarget(q,focus),source=pick.source,target=pick.target;if(!source)return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note:"Укажите, чьи именно уже полученные показания нужно предъявить."}],mode:"manual_statement_selection_required"});if(!target)return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note:"Укажите, кому предъявить выбранное показание."}],mode:"manual_statement_selection_required"});if(!TARGETS.has(source)||!known.has(source))return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note:"Эти показания ещё не получены в текущем расследовании."}],mode:"manual_statement_selection_required"});if(!TARGETS.has(target)||!known.has(target))return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note:"Этот собеседник ещё не установлен в текущем расследовании."}],mode:"manual_statement_selection_required"});const rows=entries.filter(e=>e.actor_id===source&&e.type==="statement");if(!rows.length)return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note:`В журнале пока нет отдельных зафиксированных показаний: ${targetName(source)}.`}],mode:"manual_statement_selection_required"});const selected=selectStatement(q,rows);if(!selected)return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note:`У ${targetName(source)} зафиксировано несколько ответов. Выберите конкретный: ${options(rows)}`}],mode:"manual_statement_selection_required",selection_count:rows.length});const marker=`__ML_STATEMENT_PRESENT__:${source}:${selected.entry_id}`;const ask={op:"ask_witness",target,question:marker,hypothesis:null,note:null};const operations=focus===target?[ask]:[{op:"start_interview",target,question:null,hypothesis:null,note:null},ask];return json({operations,mode:"manual_statement_confrontation_plan",planner_policy:"compound-v2+source-grounded-confrontation+retrieval-only-memory+manual-statement-confrontation",statement_source:source,statement_entry_id:selected.entry_id})}}
 if(action==="interrogate"){const question=clean(body.question,220),m=question.match(/^__ML_STATEMENT_PRESENT__:(boyfriend|mother|older_daughter|younger_daughter|second_floor_witness):([A-Za-z0-9_-]{1,50})$/);if(m){const target=clean(body.target,40),source=m[1],entryId=m[2];if(!TARGETS.has(target)||!known.has(target)||!known.has(source))return json({error:"invalid_statement_confrontation_target"},400);const entry=entries.find(e=>e.entry_id===entryId&&e.actor_id===source&&e.type==="statement");if(!entry)return json({error:"statement_not_in_memory"},400);const reply=`Вы предъявили ранее зафиксированное показание «${targetName(source)}»: ${entry.body} В доступных официальных материалах реакция этого собеседника на такое предъявление не зафиксирована.`;return json({topic:"manual_statement_confrontation",reply,unlocks:[],mode:"manual_statement_confrontation",model:"deterministic",statement_source:source,statement_entry_id:entry.entry_id,automatic_contradiction_detection:false})}}
 return forward(req,body,headers)
});
