window.addEventListener('error',e=>{const m=document.querySelector('#entryMsg');if(m)m.textContent='Ошибка запуска: '+(e.message||'неизвестная ошибка')});
const BASE='https://orknvuwknvsedjgqcfwc.supabase.co/functions/v1/';
const DUEL=BASE+'zero-copy-room-v1', SESSION=BASE+'zero-copy-session-v1', AI=BASE+'zero-copy-interrogate-v1', FINAL=BASE+'zero-copy-final-v1';
const CASE_ID='MLP002_ZERO_COPY',CASE_TITLE='Нулевая копия',CASE_PATH='/ru/cases/nulevaya-kopiya/';
const STARTER_IDS=['scene','medical','fund','catalog','repair','cond19'];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleName=r=>r==='investigator'?'Следователь':'Эксперт архива';

let boardKind='Факт',boardSelected=[];
function playSfx(id,volume=.45){try{const a=$('#'+id);if(!a)return;a.volume=volume;a.currentTime=0;void a.play()}catch{}}
function setSound(on){try{localStorage.setItem('mysterylogic:sound',on?'1':'0')}catch{};const b=$('#soundToggle'),amb=$('#ambience');if(b){b.classList.toggle('on',on);b.setAttribute('aria-pressed',String(on));b.textContent=on?'● Звук':'◔ Звук'}if(amb){amb.volume=.16;if(on){void amb.play().catch(()=>{})}else amb.pause()}}
function soundOn(){try{return localStorage.getItem('mysterylogic:sound')==='1'}catch{return false}}
function updateEvidenceTray(){const tray=$('#evidenceTray');if(!tray)return;const m=S.byId[S.selected];if(!m){tray.hidden=true;return}tray.hidden=false;$('#evidenceTrayTitle').textContent=m.title||'Материал';$('#evidenceTrayKind').textContent=m.kind||'';const th=thumbFor(S.selected),box=$('#evidenceThumb');if(th){box.innerHTML='<img src="'+esc(th)+'" alt="">'}else box.textContent='□'}
function clearEvidence(){S.selected='';$('#useEvidence').checked=false;$('#useEvidence').disabled=true;$('#presentEvidence').textContent='Материал не выбран. Откройте найденный материал, чтобы при желании предъявить его.';updateEvidenceTray();renderInterroEvidence()}
function parseBoardText(t=''){const m=String(t).match(/^§([^§]+)§\s*/);let raw=m?String(t).slice(m[0].length):String(t),lm=raw.match(/^\[#(\d+):#(\d+)\]\s*/);return {kind:m?m[1]:'Запись',text:lm?raw.slice(lm[0].length):raw,link:lm?{a:Number(lm[1]),b:Number(lm[2])}:null}}
function linkLabel(ai,bi,a,b){return '§Связь§ [#'+ai+':#'+bi+'] '+a+' ↔ '+b}

const PEOPLE={
 ratnikov:{name:'Михаил Ратников',role:'заместитель директора архива',portrait:'assets/mikhail-ratnikov.svg',context:'Руководство архива и служебные процессы',known:'Имеет административные обязанности и доступ к внутренней работе архива.'},
 denis:{name:'Денис Орлов',role:'отвечает за оцифровку архива',portrait:'assets/denis-orlov.svg',context:'Цифровые копии и фотоматериалы',known:'Работает с цифровыми изображениями архивных материалов.'},
 markin:{name:'Лев Маркин',role:'литературовед, исследователь Воронцова',portrait:'assets/lev-markin.svg',context:'Исследование наследия Воронцова',known:'Изучает тексты Воронцова и связан с научной работой вокруг рукописи.'},
 sofia:{name:'Софья Воронцова',role:'наследница',portrait:'assets/sofia-vorontsova.svg',context:'Семья и наследие Воронцова',known:'Связана с рукописью как представитель семьи Воронцова.'},
 irina:{name:'Ирина Белова',role:'директор фонда',portrait:'assets/irina-belova.svg',context:'Фонд, бюджет и подготовка выставки',known:'Отвечает за работу фонда и организационные решения.'}
};
const DOC_SOURCES={fund:'ФОНД · СЛУЖЕБНАЯ ЗАПИСКА',medical:'МЕДИЦИНСКАЯ СПРАВКА',scene:'ПРОТОКОЛ ОСМОТРА',passes:'СИСТЕМА ДОСТУПА',cards:'СЛУЖЕБНЫЙ РЕЕСТР',terminal:'ЖУРНАЛ КОМПЬЮТЕРА',access_hist:'АРХИВНЫЙ ЖУРНАЛ',market:'СПРАВКА ПО ПРОДАЖАМ',ratnikov_money:'ФИНАНСОВАЯ СПРАВКА',intermediary:'КОНТАКТЫ И СВЯЗЬ',denis_chat:'ПЕРЕПИСКА',denis_money:'ФИНАНСОВАЯ СПРАВКА',markin_draft:'ЧЕРНОВИК СТАТЬИ',sofia:'ЧЕРНОВИК СООБЩЕНИЯ',catalog:'АРХИВНАЯ КАРТОЧКА',repair:'ИСТОРИЯ РЕСТАВРАЦИИ',cond19:'АКТ ОСМОТРА',change_dates:'КОНТРОЛЬНЫЕ СЪЁМКИ',treatment:'ЖУРНАЛ РЕСТАВРАЦИИ',outgoing:'РЕЕСТР ОТПРАВОК',seal:'ПРОВЕРКА УПАКОВКИ',box_exam:'АКТ ОСМОТРА'};
function docTheme(id,kind=''){const k=String(kind).toLowerCase();if(['medical'].includes(id)||/мед/.test(k))return'medical';if(['fund','ratnikov_money','denis_money','market'].includes(id)||/финанс/.test(k))return'finance';if(['passes','cards','terminal','access_hist','change_dates','treatment','outgoing'].includes(id)||/журнал|реестр|перемещ/.test(k))return'log';if(['phone','denis_chat','sofia','intermediary'].includes(id)||/переписк|связ/.test(k))return'message';if(['catalog','repair','cond19','box_exam','seal','family_index','anna_method'].includes(id)||/архив|осмотр|реставрац/.test(k))return'archive';if(/фото/.test(k))return'photo';return'archive'}
function renderDocArtifact(m,id){
  const src=DOC_SOURCES[id]||String(m.kind||'Материал').toUpperCase();
  const body=esc(m.text||'').split(/\n+/).filter(Boolean).map(x=>'<p>'+x+'</p>').join('');
  const no=$('#viewerNoImage');if(!no)return;
  no.className='document-artifact';
  no.innerHTML=`<div class="doc-paper theme-${docTheme(id,m.kind)}"><div class="doc-topline"><span>АРХИВ «СЕВЕРНЫЙ ДОМ»</span><span>СЛУЖЕБНЫЙ МАТЕРИАЛ</span></div><div class="doc-rule"></div><div class="doc-kind">${esc(src)}</div><h2>${esc(m.title||'Материал дела')}</h2><div class="doc-body">${body}</div><div class="doc-footer"><span>Копия для материалов дела</span><span class="doc-stamp">СЕВЕРНЫЙ ДОМ</span></div></div>`;
}

const KEY='mysterylogic:partner-premium:browser-key',NAME='mysterylogic:partner-premium:player-name';
let S={code:new URLSearchParams(location.search).get('room')?.trim().toUpperCase()||'',role:'',key:getKey(),state:null,revision:0,byId:{},selected:'',demo:false,demoGuestKey:'',_activeKey:'',starter:[]},lobbyTimer=null,syncTimer=null;
function randHex(n){return[...crypto.getRandomValues(new Uint8Array(n))].map(v=>v.toString(16).padStart(2,'0')).join('')}
function getKey(){let v='';try{v=localStorage.getItem(KEY)||''}catch{}if(!/^[a-f0-9]{48}$/.test(v)){v=randHex(24);try{localStorage.setItem(KEY,v)}catch{}}return v}
function savedName(){try{return localStorage.getItem(NAME)||''}catch{return''}} function saveName(v){try{localStorage.setItem(NAME,v)}catch{}}
async function post(url,body,key=S.key,timeout=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{let r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},cache:'no-store',credentials:'omit',signal:c.signal,body:JSON.stringify({...body,browserKey:key})});let x={};try{x=await r.json()}catch{}if(!r.ok){let e=new Error(x.error||('HTTP '+r.status));e.code=x.error||'';throw e}return x}catch(e){if(e?.name==='AbortError'){let x=new Error('network_timeout');x.code='network_timeout';throw x}throw e}finally{clearTimeout(t)}}
const duel=(action,extra={},key=S.key)=>post(DUEL,{action,browserKey:key,code:S.code||undefined,...extra},key);
const session=(action='status',extra={},key=S.key)=>post(SESSION,{action,code:S.code,browserKey:key,...extra},key);
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function only(id){['intro','lobby','game'].forEach(x=>$('#'+x).hidden=x!==id)}
function roomUrl(){let u=new URL(location.href);u.search='';u.searchParams.set('room',S.code);return u.toString()}
function setUrl(){history.replaceState(null,'',S.code?'?room='+encodeURIComponent(S.code):location.pathname)}
function human(e){return({room_not_found:'Комната не найдена.',room_full:'В комнате уже два игрока.',room_expired:'Срок комнаты истёк.',not_joined:'Сначала войдите в комнату.',origin_not_allowed:'Тестовый адрес пока не разрешён сервером.',network_timeout:'Сервер не ответил вовремя. Повторите действие.',material_not_available:'Этот материал недоступен вашей роли.',room_rate_limited:'Слишком много тестовых комнат. Подождите немного.'})[e?.code||e?.message]||String(e?.message||e)}
function setEntry(t=''){$('#entryMsg').textContent=t}
function showView(name){$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));$('.navitem').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='materials')renderMaterials();if(name==='people'){syncPersonUI();renderInterroEvidence()}if(name==='board')requestAnimationFrame(renderBoardLinks);window.scrollTo({top:0,behavior:'smooth'})}
async function createRoom(){let btn=$('#createBtn'),name=$('#playerName').value.trim()||savedName()||'Следователь';btn.disabled=true;setEntry('Создаём комнату…');try{let v=await post(DUEL,{action:'create',browserKey:S.key,caseId:CASE_ID,caseTitle:CASE_TITLE,casePath:CASE_PATH,playerName:name});saveName(name);S.code=v.room.code;S.demo=false;setUrl();showLobby(v)}catch(e){setEntry('Не удалось создать комнату: '+human(e))}finally{btn.disabled=false}}
async function joinRoom(){let code=$('#roomCode').value.trim().toUpperCase(),name=$('#playerName').value.trim()||savedName()||'Эксперт';if(!/^[A-HJ-NP-Z2-9]{8}$/.test(code)){toast('Введите восьмизначный код комнаты');return}let btn=$('#joinBtn');btn.disabled=true;setEntry('Подключаемся…');try{S.code=code;let v=await duel('join',{playerName:name});saveName(name);setUrl();if(v.bothJoined)await beginGame(v);else showLobby(v)}catch(e){setEntry('Не удалось войти: '+human(e));S.code=''}finally{btn.disabled=false}}
function showLobby(v={}){only('lobby');$('#lobbyCode').textContent=S.code;$('#lobbyStatus').textContent=v.bothJoined?'Второй игрок подключён. Открываем дело…':'Ждём второго игрока…';clearInterval(lobbyTimer);lobbyTimer=setInterval(pollLobby,1800);if(v.bothJoined)beginGame(v)}
async function pollLobby(){try{let v=await duel('status');$('#lobbyStatus').textContent=v.bothJoined?'Второй игрок подключён. Открываем дело…':'Ждём второго игрока…';if(v.bothJoined)await beginGame(v)}catch(e){$('#lobbyStatus').textContent=human(e)}}
async function beginGame(prefill=null,key=S.key){clearInterval(lobbyTimer);S._activeKey=key;S.role=prefill?.me?.role||prefill?.role||S.role||'investigator';S.state=prefill?.state||S.state||{version:1,shared:{evidence:[],board:[],timeline:[],hypotheses:[]},mine:{evidence:[],notes:[]},interviews:{},final:null};S.revision=prefill?.revision||S.revision||1;only('game');render(prefill?.bothJoined??true);showView('overview');requestAnimationFrame(()=>$('#game').scrollIntoView({block:'start'}));duel('start',{},key).catch(()=>{});try{let x=await session('status',{},key);S.role=x.role;S.state=x.state;S.revision=x.revision||1;await hydrateKnown();await loadStarters();render(x.bothJoined)}catch(e){toast('Связь с сервером восстанавливается: '+human(e));await loadStarters()}clearInterval(syncTimer);syncTimer=setInterval(()=>sync(),3000)}
async function inspectInvite(){if(!/^[A-HJ-NP-Z2-9]{8}$/.test(S.code)){S.code='';return}let dc=sessionStorage.getItem('zc_demo_code'),ck=sessionStorage.getItem('zc_demo_creator'),gk=sessionStorage.getItem('zc_demo_guest');if(dc===S.code&&/^[a-f0-9]{48}$/.test(ck||'')&&/^[a-f0-9]{48}$/.test(gk||'')){S.demo=true;S._activeKey=ck;await beginGame({me:{role:'investigator'},bothJoined:true},ck);return}only('intro');$('#roomCode').value=S.code;setEntry('Комната '+S.code+'. Введите имя и нажмите «Войти по коду».')}
async function demo(){let btn=$('#demoBtn');btn.disabled=true;setEntry('Открываем демонстрацию…');try{let a=randHex(24),b=randHex(24);let v=await post(DUEL,{action:'demo_create',playerName:'Следователь',guestKey:b,guestName:'Эксперт архива'},a);S.code=v.room.code;S.demo=true;S.demoGuestKey=b;S._activeKey=a;sessionStorage.setItem('zc_demo_creator',a);sessionStorage.setItem('zc_demo_guest',b);sessionStorage.setItem('zc_demo_code',S.code);await beginGame(v,a);toast('Демо открыто. Можно переключать обе роли.')}catch(e){setEntry('Демо не открылось: '+human(e))}finally{btn.disabled=false}}
async function switchDemoRole(){if(!S.demo)return;let ck=sessionStorage.getItem('zc_demo_creator'),gk=sessionStorage.getItem('zc_demo_guest');S._activeKey=S.role==='investigator'?gk:ck;await beginGame({me:{role:S.role==='investigator'?'archivist':'investigator'},bothJoined:true},S._activeKey)}
async function sync(){if(!S.code||$('#game').hidden)return;let key=S._activeKey||S.key;try{let x=await session('status',{},key);let roleChanged=S.role!==x.role;S.role=x.role;S.state=x.state;S.revision=x.revision;if(roleChanged){S.byId={};await loadStarters()}render(x.bothJoined)}catch{}}
function mine(){return S.state?.mine||{evidence:[],notes:[]}}
async function investigate(action,extra={}){let key=S._activeKey||S.key;return post(DUEL,{action,code:S.code,...extra},key,12000)}
async function loadStarters(){try{let x=await investigate('meta',{ids:STARTER_IDS});S.starter=x.results||[];for(const m of S.starter)S.byId[m.id]=m;renderStarters()}catch{S.starter=[];renderStarters()}}
async function hydrateKnown(){let ids=(mine().evidence||[]).filter(id=>!/^Z\d+$/.test(id));if(!ids.length)return;try{let x=await investigate('meta',{ids});for(const m of x.results||[])S.byId[m.id]=m}catch{}}
function renderStarters(){let html=S.starter.map(m=>`<button class="starter" data-id="${m.id}">${thumbFor(m.id)?`<span class="starter-thumb"><img class="starter-thumb-img" src="${esc(thumbFor(m.id))}" alt=""></span>`:''}<span class="starter-copy"><b>${esc(m.title)}</b><small>${esc(m.kind)} · открыть материал</small></span></button>`).join('')||'<p class="muted">Стартовые материалы загружаются…</p>';$('#starterMaterials').innerHTML=html;$('#starterMaterialsFull').innerHTML=S.starter.map(m=>materialRow(m,true)).join('')||'<p class="muted">Стартовые материалы загружаются…</p>';$$('#starterMaterials [data-id],#starterMaterialsFull [data-id]').forEach(b=>b.onclick=()=>openMaterial(b.dataset.id,true))}
function materialRow(m,starter=false){let th=thumbFor(m.id);return `<button class="material-row" data-id="${m.id}">${th?`<span class="row-thumb"><img class="row-thumb-img" src="${esc(th)}" alt=""></span>`:`<span class="docicon">${starter?'I':'+'}</span>`}<span><b>${esc(m.title)}</b><small>${esc(m.kind)}${starter?' · доступно с начала':' · найдено вами'}</small></span></button>`}
function render(both){if(!S.state)return;$('#badge').innerHTML=roleName(S.role)+' · комната '+esc(S.code)+(S.demo?'<span class="demo-badge">ДЕМО</span>':'')+(S.demo?' <button id="demoSwitch" class="demo-switch">Сменить роль</button>':'');if(S.demo)$('#demoSwitch').onclick=switchDemoRole;$('#partnerStatus').textContent=both?'Напарник подключён':'Напарник ещё не подключился';$('#roleBrief').textContent=S.role==='investigator'?'Вы — следователь. Вам доступны документы о людях, служебных входах, событиях вечера и других обстоятельствах дела. Проверяйте любые версии и сами решайте, какие факты связаны между собой.':'Вы — эксперт архива. Вам доступны документы о самой рукописи: её состоянии, страницах, реставрационных работах и перемещениях внутри архива. Проверяйте любые версии и сами решайте, какие изменения имеют значение.';renderMaterials();renderBoard();renderNotes();renderStarters();renderInterroEvidence();syncPersonUI()}
function renderMaterials(){let starterSet=new Set(S.starter.map(m=>m.id));let ids=(mine().evidence||[]).filter(id=>!/^Z\d+$/.test(id)&&!starterSet.has(id));$('#foundCount').textContent=String((mine().evidence||[]).filter(id=>!/^Z\d+$/.test(id)).length);$('#found').innerHTML=ids.map(id=>{let m=S.byId[id];return m?materialRow(m,false):`<button class="material-row" data-id="${id}"><span class="docicon">+</span><span><b>${esc(id)}</b><small>Открыть повторно</small></span></button>`}).join('')||'<p class="muted">Новых материалов пока нет. Если хотите проверить человека, дату, документ, место или событие, воспользуйтесь поиском.</p>';$('#found [data-id]').forEach(b=>b.onclick=()=>openMaterial(b.dataset.id,true));renderInterroEvidence()}

function interroMaterials(){let ids=[...new Set([...S.starter.map(m=>m.id),...(mine().evidence||[]).filter(id=>!/^Z\d+$/.test(id))])];return ids.map(id=>S.byId[id]||S.starter.find(m=>m.id===id)).filter(Boolean)}
async function selectEvidence(id){let m=S.byId[id]||S.starter.find(x=>x.id===id);if(!m)return;let opened=(mine().evidence||[]).includes(id);if(!opened){await openMaterial(id,false);toast('Сначала изучите материал — после этого его можно предъявить');return}S.selected=id;S.byId[id]={...S.byId[id],...m};$('#presentEvidence').textContent='Предъявить при следующем вопросе: '+m.title;$('#useEvidence').disabled=false;$('#useEvidence').checked=true;updateEvidenceTray();renderInterroEvidence();playSfx('sfxPresent',.28)}
function renderInterroEvidence(){let box=$('#interroEvidenceGrid');if(!box)return;let mats=interroMaterials();box.innerHTML=mats.map(m=>{let th=thumbFor(m.id),active=S.selected===m.id;let opened=(mine().evidence||[]).includes(m.id);return `<button type="button" class="interro-evidence-card${active?' active':''}${opened?' opened':' unopened'}" data-evidence-id="${esc(m.id)}">${th?`<img src="${esc(th)}" alt="">`:`<span class="mini-doc theme-${docTheme(m.id,m.kind)}">DOC</span>`}<span><b>${esc(m.title)}</b><small>${esc(m.kind)} · ${opened?'можно предъявить':'сначала открыть'}</small></span></button>`}).join('')||'<p class="muted">Откройте материалы дела — доступные документы появятся здесь.</p>';$('#interroEvidenceGrid [data-evidence-id]').forEach(b=>b.onclick=()=>selectEvidence(b.dataset.evidenceId))}
function boardVisualFor(text=''){let mm=String(text).match(/Материал «([^»]+)»/);if(!mm)return'';let found=Object.values(S.byId).find(m=>m&&m.title===mm[1])||S.starter.find(m=>m.title===mm[1]);if(!found)return'';let th=thumbFor(found.id);return th?`<div class="board-attachment photo"><img src="${esc(th)}" alt=""><span>${esc(found.title)}</span></div>`:`<div class="board-attachment paper theme-${docTheme(found.id,found.kind)}"><span class="paper-clip"></span><b>${esc(found.title)}</b><small>${esc(found.kind)}</small></div>`}
function renderBoard(){let arr=S.state?.shared?.board||[],shown=arr.map((x,i)=>({...x,_i:i,...parseBoardText(x.text)})).reverse();$('#board').innerHTML=shown.map(x=>{let link=x.kind==='Связь';return `<article class="board-note kind-${esc(x.kind.toLowerCase())}${boardSelected.includes(x._i)?' selected':''}${link?' link-note':''}" data-board-index="${x._i}"><span class="board-pin"></span>${link?'':boardVisualFor(x.text)}<div class="board-note-top"><span class="board-tag">${esc(x.kind)}</span><b>${roleName(x.by)}</b></div><p>${esc(x.text)}</p></article>`}).join('')||'<div class="stage-empty"><h3>Доска пока пуста</h3><p>Добавляйте только те связи и версии, которые считаете полезными сами.</p></div>';$('#board [data-board-index]').forEach(el=>el.onclick=()=>{let i=Number(el.dataset.boardIndex);if(boardSelected.includes(i))boardSelected=boardSelected.filter(x=>x!==i);else{if(boardSelected.length>=2)boardSelected.shift();boardSelected.push(i)}renderBoard();const b=$('#linkBoardBtn');if(b)b.disabled=boardSelected.length!==2});renderBoardLinks()}
function renderBoardLinks(){let svg=$('#boardLinks');if(!svg)return;svg.innerHTML='';const links=(S.state?.shared?.board||[]).map(x=>parseBoardText(x.text)).filter(x=>x.kind==='Связь'&&x.link);if(!links.length)return;let w=svg.clientWidth||700,h=svg.clientHeight||500;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);links.slice(-10).forEach(x=>{let a=$(`#board [data-board-index="${x.link.a}"]`),b=$(`#board [data-board-index="${x.link.b}"]`);if(!a||!b)return;let ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),sr=svg.getBoundingClientRect();let x1=ar.left-sr.left+ar.width/2,y1=ar.top-sr.top+ar.height/2,x2=br.left-sr.left+br.width/2,y2=br.top-sr.top+br.height/2;svg.insertAdjacentHTML('beforeend',`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}"/>`)})}
function renderNotes(){let arr=mine().notes||[];$('#notes').innerHTML=arr.slice().reverse().map(x=>`<article><p>${esc(x.text)}</p></article>`).join('')||'<p class="muted">Заметок пока нет.</p>'}
async function search(){let q=$('#query').value.trim();if(q.length<2)return;let b=$('#searchBtn');b.disabled=true;b.textContent='Ищем…';try{let x=await investigate('search',{query:q});for(const m of x.results||[])S.byId[m.id]=m;$('#results').innerHTML=(x.results||[]).map(m=>`<button class="hit" data-id="${m.id}"><span class="docicon">⌕</span><span><b>${esc(m.title)}</b><small>${esc(m.kind)}</small></span></button>`).join('')||'<p class="muted">По этому запросу в доступных вам источниках ничего не найдено. Попробуйте другую формулировку или другую версию.</p>';$$('#results .hit').forEach(el=>el.onclick=()=>openMaterial(el.dataset.id,true))}catch(e){toast('Поиск не выполнен: '+human(e))}finally{b.disabled=false;b.textContent='Искать'}}
const images={scene:'assets/archive-lab-premium.png',camera:'assets/capture-series-premium.png',catalog:'assets/manuscript_close.jpg',photosession:'assets/capture-series-premium.png',capture1:'assets/capture_2208.svg',capture2:'assets/capture_2209.svg',p47a:'assets/page47_2019.svg',p47b:'assets/page47_2026.svg',seal_visual:'assets/seal.svg'};
function thumbFor(id){return images[id]||''}
async function patch(p){let key=S._activeKey||S.key;for(let i=0;i<2;i++){try{let x=await session('patch',{patch:p},key);S.state=x.state;S.revision=x.revision;render(true);return x}catch(e){if((e.code||e.message)!=='state_conflict'||i)throw e;let fresh=await session('status',{},key);S.role=fresh.role;S.state=fresh.state;S.revision=fresh.revision}}}
function shareMaterialToBoard(m){let prefix='Материал «'+m.title+'»';let box=$('#boardInput');boardKind='Факт';syncBoardKind();box.value=prefix+' — ';showView('board');requestAnimationFrame(()=>{box.focus();box.setSelectionRange(box.value.length,box.value.length)});toast('Добавьте своё наблюдение и отправьте его напарнику')}
function stageMaterial(m,id){S.selected=id;let src=m.image||images[id]||'';$('#materialStage').classList.remove('empty-stage');const paper=`<div class="stage-paper theme-${docTheme(id,m.kind)}"><div class="doc-kind">${esc(DOC_SOURCES[id]||m.kind||'Материал дела')}</div><h2>${esc(m.title)}</h2><div class="doc-body">${esc(m.text)}</div></div>`;$('#materialStage').innerHTML=`<div class="stage-doc"><div class="stage-media">${src?`<img src="${esc(src)}" alt="${esc(m.title)}">`:paper}</div><div class="stage-info"><div class="eyebrow">${esc(m.kind)}</div><h2>${esc(m.title)}</h2><p>${esc(m.text)}</p><div class="stage-actions"><button class="primary" id="stagePresent">Выбрать для предъявления</button><button class="secondary" id="stageBoard">Вынести на общую доску</button><button class="secondary" id="stageViewer">Открыть крупно</button></div></div></div>`;$('#stagePresent').onclick=()=>{S.selected=id;S.byId[id]={...S.byId[id],...m};$('#presentEvidence').textContent='Предъявить при следующем вопросе: '+m.title;$('#useEvidence').disabled=false;$('#useEvidence').checked=true;updateEvidenceTray();playSfx('sfxPresent');toast('Материал выбран для предъявления')};$('#stageBoard').onclick=()=>shareMaterialToBoard(m);$('#stageViewer').onclick=()=>showViewer(m,id)}
function showViewer(m,id){S.selected=id;S.byId[id]={...S.byId[id],...m};$('#viewerTitle').textContent=m.title;$('#viewerKind').textContent=m.kind;$('#viewerText').textContent=m.text;let im=$('#viewerImage'),no=$('#viewerNoImage'),src=m.image||images[id]||'';if(src){im.src=src;im.hidden=false;no.hidden=true}else{im.hidden=true;im.removeAttribute('src');no.hidden=false;renderDocArtifact(m,id)}$('#viewer').classList.add('open');$('#presentEvidence').textContent='Предъявить при следующем вопросе: '+m.title;$('#useEvidence').disabled=false;$('#useEvidence').checked=false;updateEvidenceTray();playSfx('sfxOpen',.32);$('#shareViewerBoard').onclick=()=>{$('#viewer').classList.remove('open');shareMaterialToBoard(m)}}
async function openMaterial(id,goMaterials=false){try{let x=await investigate('open',{id}),m=x.material;S.byId[id]={id:m.id,title:m.title,kind:m.kind,text:m.text,image:m.image||null};await sync();if(goMaterials)showView('materials');stageMaterial(m,id);showViewer(m,id)}catch(e){toast('Материал не открыт: '+human(e))}}
async function addBoard(){let t=$('#boardInput').value.trim();if(!t)return;try{await patch({board_note:`§${boardKind}§ ${t}`});$('#boardInput').value='';playSfx('sfxBoard',.4);showView('board')}catch(e){toast(human(e))}}
function syncBoardKind(){$$('[data-board-kind]').forEach(b=>b.classList.toggle('active',b.dataset.boardKind===boardKind))}
async function linkBoard(){if(boardSelected.length!==2)return;let arr=S.state?.shared?.board||[],ai=boardSelected[0],bi=boardSelected[1],a=parseBoardText(arr[ai]?.text||''),b=parseBoardText(arr[bi]?.text||'');let aa=a.text.slice(0,58),bb=b.text.slice(0,58);try{await patch({board_note:linkLabel(ai,bi,aa,bb)});boardSelected=[];playSfx('sfxBoard',.5);renderBoard();toast('Связь добавлена на общую доску')}catch(e){toast(human(e))}}
async function addNote(){let t=$('#noteInput').value.trim();if(!t)return;try{await patch({private_note:t});$('#noteInput').value='';showView('notes')}catch(e){toast(human(e))}}
function syncPersonUI(){let val=$('#character').value,p=PEOPLE[val]||{},name=p.name||$(`#character option[value="${val}"]`)?.textContent||'';$('#activePersonName').textContent=name;if($('#activePersonRole'))$('#activePersonRole').textContent=p.role||'';if($('#activePersonPortrait')){$('#activePersonPortrait').src=p.portrait||'';$('#activePersonPortrait').alt=name}if($('#dossierRole'))$('#dossierRole').textContent=p.role||'';if($('#dossierContext'))$('#dossierContext').textContent=p.context||'';if($('#dossierKnown'))$('#dossierKnown').textContent=p.known||'';$('.suspect').forEach(b=>b.classList.toggle('active',b.dataset.suspect===val));renderInterroEvidence()}
async function talk(){let q=$('#question').value.trim();if(!q)return;let btn=$('#talkBtn');btn.disabled=true;btn.textContent='Собеседник отвечает…';try{let key=S._activeKey||S.key,eid=$('#useEvidence').checked?S.selected:'',x=await post(AI,{code:S.code,suspect_id:$('#character').value,question:q,evidence_id:eid},key);let empty=$('#dialog .dialog-empty');if(empty)empty.remove();let n=document.createElement('article');n.className='dialog';let p=PEOPLE[$('#character').value]||{},ev=eid&&S.byId[eid]?`<div class="dialog-evidence">Предъявлено: ${esc(S.byId[eid].title)}</div>`:'';n.innerHTML=`<div class="dialog-person"><img src="${esc(p.portrait||'')}" alt=""><div><b>${esc(p.name||'Собеседник')}</b><small>${esc(p.role||'')}</small></div></div><p class="q">Вы: ${esc(q)}</p>${ev}<p class="answer">${esc(x.reply)}</p>`;$('#dialog').prepend(n);$('#question').value='';$('#useEvidence').checked=false;if(eid)playSfx('sfxPresent',.35);await sync()}catch(e){toast('Разговор не состоялся: '+human(e))}finally{btn.disabled=false;btn.textContent='Спросить'}}
const FINAL_TABS=['who','why','how','where','when','evidence','lies'];let finalTab='who';
function showFinalTab(key){if(!FINAL_TABS.includes(key))key='who';finalTab=key;$('[data-final-tab]').forEach(b=>b.classList.toggle('active',b.dataset.finalTab===key));$('[data-final-panel]').forEach(p=>p.classList.toggle('active',p.dataset.finalPanel===key));let i=FINAL_TABS.indexOf(key),prev=$('#finalPrev'),next=$('#finalNext');if(prev)prev.disabled=i===0;if(next)next.disabled=i===FINAL_TABS.length-1}
function moveFinal(dir){let i=FINAL_TABS.indexOf(finalTab);showFinalTab(FINAL_TABS[Math.max(0,Math.min(FINAL_TABS.length-1,i+dir))])}
async function submitFinal(){let a={};['who','why','how','where','when','evidence','lies'].forEach(k=>a[k]=$('#f_'+k).value);let b=$('#finalBtn');b.disabled=true;b.textContent='Проверяем реконструкцию…';try{let key=S._activeKey||S.key,x=await post(FINAL,{code:S.code,answers:a},key);$('#finalResult').textContent=x.message||'';if(x.passed&&x.reveal){$('#reveal').innerHTML=`<div class="reveal-head"><div><div class="eyebrow">Дело реконструировано</div><h2>${esc(x.reveal.title)}</h2></div><div class="reveal-seal">✓</div></div><div class="reveal-timeline">${(x.reveal.paragraphs||[]).map((p,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><p>${esc(p)}</p></article>`).join('')}</div>`;$('#reveal').hidden=false;playSfx('sfxFinal',.5);$('#reveal').scrollIntoView({behavior:'smooth'})}}catch(e){$('#finalResult').textContent='Проверка временно недоступна: '+human(e)}finally{b.disabled=false;b.textContent='Передать всю реконструкцию на проверку'}}
$('#playerName').value=savedName();$('#createBtn').onclick=createRoom;$('#joinBtn').onclick=joinRoom;$('#demoBtn').onclick=demo;$('#copyCodeBtn').onclick=async()=>{try{await navigator.clipboard.writeText(S.code);toast('Код скопирован')}catch{toast(S.code)}};$('#copyInviteBtn').onclick=async()=>{try{await navigator.clipboard.writeText(roomUrl());toast('Ссылка скопирована')}catch{toast(roomUrl())}};$('#leaveLobbyBtn').onclick=()=>{clearInterval(lobbyTimer);S.code='';history.replaceState(null,'',location.pathname);only('intro')};
$$('.navitem,.jump').forEach(b=>b.onclick=()=>showView(b.dataset.view));
$$('[data-suspect]').forEach(b=>b.addEventListener('click',()=>{showView('people');$('#character').value=b.dataset.suspect;syncPersonUI()}));
$('#character').onchange=()=>{syncPersonUI();playSfx('sfxSwitch',.25)};$('[data-final-tab]').forEach(b=>b.onclick=()=>showFinalTab(b.dataset.finalTab));if($('#finalPrev'))$('#finalPrev').onclick=()=>moveFinal(-1);if($('#finalNext'))$('#finalNext').onclick=()=>moveFinal(1);showFinalTab('who');$('#searchBtn').onclick=search;$('#query').onkeydown=e=>{if(e.key==='Enter')search()};$('#talkBtn').onclick=talk;$('#boardBtn').onclick=addBoard;$('#noteBtn').onclick=addNote;$('#finalBtn').onclick=submitFinal;$('#closeViewer').onclick=$('#backViewer').onclick=()=>$('#viewer').classList.remove('open');$('#openInMaterials').onclick=()=>{$('#viewer').classList.remove('open');showView('materials')};
$$('[data-board-kind]').forEach(b=>b.onclick=()=>{boardKind=b.dataset.boardKind;syncBoardKind()});syncBoardKind();if($('#linkBoardBtn'))$('#linkBoardBtn').onclick=linkBoard;if($('#clearEvidence'))$('#clearEvidence').onclick=clearEvidence;if($('#soundToggle')){const pref=soundOn();$('#soundToggle').onclick=()=>setSound(!$('#soundToggle').classList.contains('on'));setSound(false);if(pref)document.addEventListener('pointerdown',()=>setSound(true),{once:true})}
(async()=>{if(S.code)await inspectInvite()})();