window.addEventListener('error',e=>{const m=document.querySelector('#entryMsg');if(m)m.textContent='Ошибка запуска: '+(e.message||'неизвестная ошибка')});
const BASE='https://orknvuwknvsedjgqcfwc.supabase.co/functions/v1/';
const DUEL=BASE+'zero-copy-room-v1', SESSION=BASE+'zero-copy-session-v1', AI=BASE+'zero-copy-interrogate-v1', FINAL=BASE+'zero-copy-final-v1';
const CASE_ID='MLP002_ZERO_COPY',CASE_TITLE='Нулевая копия',CASE_PATH='/ru/cases/nulevaya-kopiya/';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleName=r=>r==='investigator'?'Следователь':'Эксперт архива';
const KEY='mysterylogic:partner-premium:browser-key',NAME='mysterylogic:partner-premium:player-name';
let S={code:new URLSearchParams(location.search).get('room')?.trim().toUpperCase()||'',role:'',key:getKey(),state:null,revision:0,byId:{},selected:'',demo:false,demoGuestKey:'',_activeKey:''},lobbyTimer=null,syncTimer=null;
function randHex(n){return[...crypto.getRandomValues(new Uint8Array(n))].map(v=>v.toString(16).padStart(2,'0')).join('')}
function getKey(){let v='';try{v=localStorage.getItem(KEY)||''}catch{}if(!/^[a-f0-9]{48}$/.test(v)){v=randHex(24);try{localStorage.setItem(KEY,v)}catch{}}return v}
function savedName(){try{return localStorage.getItem(NAME)||''}catch{return''}}function saveName(v){try{localStorage.setItem(NAME,v)}catch{}}
async function post(url,body,key=S.key,timeout=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{let r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},cache:'no-store',credentials:'omit',signal:c.signal,body:JSON.stringify({...body,browserKey:key})});let x={};try{x=await r.json()}catch{}if(!r.ok){let e=new Error(x.error||('HTTP '+r.status));e.code=x.error||'';throw e}return x}catch(e){if(e?.name==='AbortError'){let x=new Error('network_timeout');x.code='network_timeout';throw x}throw e}finally{clearTimeout(t)}}
const duel=(action,extra={},key=S.key)=>post(DUEL,{action,browserKey:key,code:S.code||undefined,...extra},key);
const session=(action='status',extra={},key=S.key)=>post(SESSION,{action,code:S.code,browserKey:key,...extra},key);
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function only(id){['intro','lobby','game'].forEach(x=>$('#'+x).hidden=x!==id)}
function roomUrl(){let u=new URL(location.href);u.search='';u.searchParams.set('room',S.code);return u.toString()}
function setUrl(){history.replaceState(null,'',S.code?'?room='+encodeURIComponent(S.code):location.pathname)}
function human(e){return({room_not_found:'Комната не найдена.',room_full:'В комнате уже два игрока.',room_expired:'Срок комнаты истёк.',not_joined:'Сначала войдите в комнату.',origin_not_allowed:'Тестовый адрес пока не разрешён сервером.',network_timeout:'Сервер не ответил вовремя. Повторите действие.',upstream_unavailable:'Сервер материалов временно не получил подтверждение комнаты.',material_not_available:'Этот материал недоступен вашей роли.'})[e?.code||e?.message]||String(e?.message||e)}
function setEntry(t=''){$('#entryMsg').textContent=t}
async function createRoom(){let btn=$('#createBtn'),name=$('#playerName').value.trim()||savedName()||'Следователь';btn.disabled=true;setEntry('Создаём комнату…');try{let v=await post(DUEL,{action:'create',browserKey:S.key,caseId:CASE_ID,caseTitle:CASE_TITLE,casePath:CASE_PATH,playerName:name});saveName(name);S.code=v.room.code;S.demo=false;setUrl();showLobby(v)}catch(e){setEntry('Не удалось создать комнату: '+human(e))}finally{btn.disabled=false}}
async function joinRoom(){let code=$('#roomCode').value.trim().toUpperCase(),name=$('#playerName').value.trim()||savedName()||'Эксперт';if(!/^[A-HJ-NP-Z2-9]{8}$/.test(code)){toast('Введите восьмизначный код комнаты');return}let btn=$('#joinBtn');btn.disabled=true;setEntry('Подключаемся…');try{S.code=code;let v=await duel('join',{playerName:name});saveName(name);setUrl();if(v.bothJoined)await beginGame();else showLobby(v)}catch(e){setEntry('Не удалось войти: '+human(e));S.code=''}finally{btn.disabled=false}}
function showLobby(v={}){only('lobby');$('#lobbyCode').textContent=S.code;$('#lobbyStatus').textContent=v.bothJoined?'Второй игрок подключён. Открываем дело…':'Ждём второго игрока…';clearInterval(lobbyTimer);lobbyTimer=setInterval(pollLobby,1800);if(v.bothJoined)beginGame()}
async function pollLobby(){try{let v=await duel('status');$('#lobbyStatus').textContent=v.bothJoined?'Второй игрок подключён. Открываем дело…':'Ждём второго игрока…';if(v.bothJoined)await beginGame()}catch(e){$('#lobbyStatus').textContent=human(e)}}
async function beginGame(key=S.key){clearInterval(lobbyTimer);S._activeKey=key;try{await duel('start',{},key)}catch{}let x=await session('status',{},key);S.role=x.role;S.state=x.state;S.revision=x.revision||1;only('game');await hydrateKnown();render(x.bothJoined);clearInterval(syncTimer);syncTimer=setInterval(()=>sync(),3000)}
async function inspectInvite(){if(!/^[A-HJ-NP-Z2-9]{8}$/.test(S.code)){S.code='';return}let dc=sessionStorage.getItem('zc_demo_code'),ck=sessionStorage.getItem('zc_demo_creator'),gk=sessionStorage.getItem('zc_demo_guest');if(dc===S.code&&/^[a-f0-9]{48}$/.test(ck||'')&&/^[a-f0-9]{48}$/.test(gk||'')){S.demo=true;S._activeKey=ck;await beginGame(ck);return}only('intro');$('#roomCode').value=S.code;setEntry('Комната '+S.code+'. Введите имя и нажмите «Войти по коду».')}
async function demo(){let btn=$('#demoBtn');btn.disabled=true;setEntry('Открываем демонстрацию…');try{let a=randHex(24),b=randHex(24);let v=await post(DUEL,{action:'create',playerName:'Следователь'},a);S.code=v.room.code;await post(DUEL,{action:'join',code:S.code,playerName:'Эксперт архива'},b);S.demo=true;S.demoGuestKey=b;S._activeKey=a;sessionStorage.setItem('zc_demo_creator',a);sessionStorage.setItem('zc_demo_guest',b);sessionStorage.setItem('zc_demo_code',S.code);await beginGame(a);toast('Демо открыто. Можно переключать обе роли.')}catch(e){setEntry('Демо не открылось: '+human(e))}finally{btn.disabled=false}}
async function switchDemoRole(){if(!S.demo)return;let ck=sessionStorage.getItem('zc_demo_creator'),gk=sessionStorage.getItem('zc_demo_guest');S._activeKey=S.role==='investigator'?gk:ck;await beginGame(S._activeKey)}
async function sync(){if(!S.code||$('#game').hidden)return;let key=S._activeKey||S.key;try{let x=await session('status',{},key);S.role=x.role;S.state=x.state;S.revision=x.revision;render(x.bothJoined)}catch{}}
function mine(){return S.state?.mine||{evidence:[],notes:[]}}
function render(both){if(!S.state)return;$('#badge').innerHTML=roleName(S.role)+' · комната '+esc(S.code)+(S.demo?'<span class="demo-badge">ДЕМО</span>':'')+(S.demo?' <button id="demoSwitch" class="demo-switch">Сменить роль</button>':'');if(S.demo)$('#demoSwitch').onclick=switchDemoRole;$('#partnerStatus').textContent=both?'Напарник подключён':'Напарник ещё не подключился';let ids=(mine().evidence||[]).filter(id=>!/^Z\d+$/.test(id));$('#found').innerHTML=ids.map(id=>{let m=S.byId[id];return m?`<button class="material" data-id="${id}">${esc(m.title)}<small>${esc(m.kind)}</small></button>`:`<button class="material" data-id="${id}">Материал ${esc(id)}<small>Открыть повторно</small></button>`}).join('')||'<p class="muted">Пока ничего нового.</p>';document.querySelectorAll('.material').forEach(b=>b.onclick=()=>openMaterial(b.dataset.id));$('#board').innerHTML=(S.state.shared?.board||[]).slice().reverse().map(x=>`<article><b>${roleName(x.by)}</b><p>${esc(x.text)}</p></article>`).join('')||'<p class="muted">На доске пока пусто.</p>';$('#notes').innerHTML=(mine().notes||[]).slice().reverse().map(x=>`<article><p>${esc(x.text)}</p></article>`).join('')||'<p class="muted">Личные заметки видите только вы.</p>'}
async function investigate(action,extra={}){let key=S._activeKey||S.key;return post(DUEL,{action,code:S.code,...extra},key,12000)}
async function hydrateKnown(){let ids=(mine().evidence||[]).filter(id=>!/^Z\d+$/.test(id));if(!ids.length)return;try{let x=await investigate('meta',{ids});for(const m of x.results||[])S.byId[m.id]=m}catch{}}
async function search(){let q=$('#query').value.trim();if(q.length<2)return;let b=$('#searchBtn');b.disabled=true;b.textContent='Ищем…';try{let x=await investigate('search',{query:q});for(const m of x.results||[])S.byId[m.id]=m;$('#results').innerHTML=(x.results||[]).map(m=>`<button class="hit" data-id="${m.id}"><b>${esc(m.title)}</b><span>${esc(m.kind)}</span></button>`).join('')||'<p class="muted">По этому запросу в доступных вам источниках ничего ничего не найдено. Попробуйте другую формулировку или версию.</p>';document.querySelectorAll('.hit').forEach(el=>el.onclick=()=>openMaterial(el.dataset.id))}catch(e){toast('Поискне выполнен: '+human(e))}finally{b.disabled=false;b.textContent='Искать'}}
const images={capture1:'assets/capture_2208.svg',capture2:'assets/capture_2209.svg',p47a:'assets/page47_2019.svg',p47b:'assets/page47_2026.svg',seal_visual:'assets/seal.svg',photosession:'assets/capture-comparison.png',scene:'assets/archive-lab.png'};
async function patch(p){let key=S._activeKey||S.key;for(let i=0;i<2;i++){try{let x=await session('patch',{patch:p},key);S.state=x.state;S.revision=x.revision;render(true);return x}catch(e){if((e.code||e.message)!=='state_conflict'||i)throw e;let fresh=await session('status',{},key);S.role=fresh.role;S.state=fresh.state;S.revision=fresh.revision}}}
async function openMaterial(id){try{let x=await investigate('open',{id}),m=x.material;S.byId[id]={id:m.id,title:m.title,kind:m.kind,image:m.image||null};await sync();S.selected=id;$('#viewerTitle').textContent=m.title;$('#viewerKind').textContent=m.kind;$('#viewerText').textContent=m.text;let im=$('#viewerImage'),src=m.image||images[id]||'';if(src){im.src=src;im.hidden=false}else{im.hidden=true;im.removeAttribute('src')}$('#viewer').classList.add('open');$('#presentEvidence').textContent='Предъявить при следующем вопросе: '+m.title;$('#useEvidence').disabled=false;$('#useEvidence').checked=false}catch(e){toast('Материал не открыт: '+human(e))}}
async function addBoard(){let t=$('#boardInput').value.trim();if(!t)return;try{await patch({board_note:t});$('#boardInput').value=''}catch(e){toast(human(e))}}
async function addNote(){let t=$('#noteInput').value.trim();if(!t)return;try{await patch({private_note:t});$('#noteInput').value=''}catch(e){toast(human(e))}}
async function talk(){let q=$('#question').value.trim();if(!q)return;let btn=$('#talkBtn');btn.disabled=true;btn.textContent='Собеседник отвечает…';try{let key=S._activeKey||S.key,eid=$('#useEvidence').checked?S.selected:'',x=await post(AI,{code:S.code,suspect_id:$('#character').value,question:q,evidence_id:eid},key);let n=document.createElement('article');n.className='dialog';n.innerHTML=`<p class="q">Вы: ${esc(q)}</p><p>${esc(x.reply)}</p>`;$('#dialog').prepend(n);$('#question').value='';$('#useEvidence').checked=false;await sync()}catch(e){toast('Разговор не состоялся: '+human(e))}finally{btn.disabled=false;btn.textContent='Спросить'}}
async function submitFinal(){let a={};['who','why','how','where','when','evidence','lies'].forEach(k=>a[k]=$('#f_'+k).value);let b=$('#finalBtn');b.disabled=true;b.textContent='Проверяем реконструкцию…';try{let key=S._activeKey||S.key,x=await post(FINAL,{code:S.code,answers:a},key);$('#finalResult').textContent=x.message||'';if(x.passed&&x.reveal){$('#reveal').innerHTML=`<div class="gold">Разбор дела</div><h2>${esc(x.reveal.title)}</h2>${(x.reveal.paragraphs||[]).map(p=>`<p>${esc(p)}</p>`).join('')}`;$('#reveal').hidden=false;$('#reveal').scrollIntoView({behavior:'smooth'})}}catch(e){$('#finalResult').textContent='Проверка временно недоступна: '+human(e)}finally{b.disabled=false;b.textContent='Проверить реконструкцию'}}
$('#playerName').value=savedName();$('#createBtn').onclick=createRoom;$('#joinBtn').onclick=joinRoom;$('#demoBtn').onclick=demo;$('#copyCodeBtn').onclick=async()=>{try{await navigator.clipboard.writeText(S.code);toast('Код скопирован')}catch{toast(S.code)}};$('#copyInviteBtn').onclick=async()=>{try{await navigator.clipboard.writeText(roomUrl());toast('Ссылка скопирована')}catch{toast(roomUrl())}};$('#leaveLobbyBtn').onclick=()=>{clearInterval(lobbyTimer);S.code='';history.replaceState(null,'',location.pathname);only('intro')};$('#searchBtn').onclick=search;$('#query').onkeydown=e=>{if(e.key==='Enter')search()};$('#talkBtn').onclick=talk;$('#boardBtn').onclick=addBoard;$('#noteBtn').onclick=addNote;$('#finalBtn').onclick=submitFinal;$('#closeViewer').onclick=$('#backViewer').onclick=()=>$('#viewer').classList.remove('open');
(async()=>{if(S.code)await inspectInvite()})();
