import fs from 'node:fs';
import path from 'node:path';
import {ensureDir,escapeHtml,estimate} from './common.mjs';
const splitFacts=(intro)=>String(intro||'').split(/\n+|(?<=[.!?])\s+/u).map(x=>x.replace(/^[•\-]\s*/,'').trim()).filter(Boolean).slice(0,5).map((value,i)=>({label:`Факт ${i+1}`,value}));
const steps=(item)=>Array.isArray(item.explanation?.reasoningSteps)&&item.explanation.reasoningSteps.length?item.explanation.reasoningSteps.slice(0,5):String(item.explanation?.fullReason||'').split(/(?<=[.!?])\s+/u).filter(Boolean).slice(0,4);
const head=(item)=>`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#08111d"><meta name="description" content="Дело №${item.number}: ${escapeHtml(item.title)}"><link rel="canonical" href="https://valera2872.github.io/ktovret-web/${item.path}"><link rel="icon" href="../../assets/ml-mark.svg" type="image/svg+xml"><link rel="stylesheet" href="../../assets/mysterylogic.css"><link rel="stylesheet" href="../../assets/full-catalog.css"><link rel="stylesheet" href="../../ktovret-game/assets/style.css"><title>${escapeHtml(item.title)} — Кто врёт?</title></head>`;
const brand='<div class="ml-brand-strip"><div class="ml-brand-strip-inner"><a class="ml-brand" href="../../"><span class="ml-brand-mark">ML</span><span class="ml-brand-copy"><strong>Mystery Logic</strong><small>Interactive investigations</small></span></a><nav class="ml-brand-strip-nav"><a href="../../kto-vret/">Кто врёт?</a><a href="../../dela/">Все дела</a></nav></div></div>';
const choose=(items,min,max,start=0,picked=[],result=[])=>{if(picked.length>=min&&picked.length<=max)result.push([...picked]);if(picked.length===max)return result;for(let i=start;i<items.length;i++)choose(items,min,max,i+1,[...picked,items[i]],result);return result;};
const normalizeStage=(stage)=>({id:stage.id,prompt:stage.prompt,instruction:stage.instruction||'',selectionMode:stage.selectionMode||'single',minSelections:stage.minSelections||1,maxSelections:stage.maxSelections||1,options:(stage.options||[]).map(option=>({id:option.id,label:option.label,detail:option.detail||''})),correctOptionIds:stage.correctOptionIds||[]});
const flattenStages=(item)=>{
 const source=Array.isArray(item.answerStages)&&item.answerStages.length?item.answerStages.map(normalizeStage):[{id:'liar',prompt:item.question||'Кто говорит неправду?',instruction:'Сопоставьте материалы дела со всеми показаниями.',selectionMode:'single',minSelections:1,maxSelections:1,options:item.characters.map(x=>({id:x.id,label:x.name,detail:''})),correctOptionIds:[item.correctOptionId]}];
 if(source.length===1&&source[0].maxSelections===1&&source[0].selectionMode!=='multiple')return source;
 const variants=source.map(stage=>choose(stage.options,stage.minSelections,stage.maxSelections).map(selection=>({stageId:stage.id,label:`${stage.prompt}: ${selection.map(option=>option.label).join(', ')}`,ids:selection.map(option=>option.id),correct:selection.length===stage.correctOptionIds.length&&stage.correctOptionIds.every(id=>selection.some(option=>option.id===id))})));
 let combinations=[[]];for(const list of variants)combinations=combinations.flatMap(prefix=>list.map(value=>[...prefix,value]));if(combinations.length>240)throw new Error(`Слишком много веб-комбинаций в ${item.id}: ${combinations.length}`);
 const options=combinations.map((parts,index)=>({id:`conclusion_${index+1}`,label:parts.map(part=>part.label).join(' · '),detail:'',correct:parts.every(part=>part.correct)}));const correct=options.filter(option=>option.correct);if(correct.length!==1)throw new Error(`Неоднозначная итоговая комбинация в ${item.id}`);
 return[{id:'complete_conclusion',prompt:item.question||'Выберите полное заключение',instruction:'Выберите вариант, который правильно объединяет все этапы ответа.',selectionMode:'single',minSelections:1,maxSelections:1,options:options.map(({correct:ignored,...option})=>option),correctOptionIds:[correct[0].id]}];
};
function config(item){const statements=item.characters.map(x=>`${x.name}: «${x.statement}»`).join('\n\n');return{storageKey:item.storageKey,permalink:'',siteName:'Mystery Logic',case:{id:item.id,title:item.title,caseNumber:`№ ${item.number}`,estimatedMinutes:estimate(item.difficulty),witnessCount:item.characters.length,difficulty:item.difficulty||'Среднее',category:item.category||'Логика',logicType:item.logicType||item.category||'Логическое противоречие',materialsLabel:item.materialsLabel||'Материалы дела',intro:item.intro,question:item.question||'Кто говорит неправду?',timeline:[{time:'Досье',title:'Обстоятельства дела',detail:item.intro,source:'Материалы бюро'}],facts:splitFacts(item.intro),characters:item.characters.length?[{id:'dossier',name:'Показания',role:`${item.characters.length} свидетеля`,statement:statements}]:[],answerStages:flattenStages(item),explanation:{shortReason:item.explanation.shortReason||item.explanation.fullReason,fullReason:item.explanation.fullReason,reasoningSteps:steps(item),evidenceFragments:item.explanation.evidenceFragments||[]}}};}
const playable=(item)=>`${head(item)}<body>${brand}<main class="ktv-game-shell" data-ktv-root data-case-id="${escapeHtml(item.id)}"><noscript>Включите JavaScript.</noscript></main><script src="../../assets/generated/cases-index.js?v=0.9.1"></script><script src="../../assets/dossier-model.js?v=0.9.1"></script><script>window.KtoVretWeb=${JSON.stringify(config(item)).replaceAll('<','\\u003c')};window.KtoVretWeb.permalink=location.href;</script><script src="../../ktovret-game/assets/app.js?v=0.9.1"></script><script src="../../ktovret-game/assets/performance.js?v=0.9.1"></script><script src="../../assets/case-adapter.js?v=0.9.1"></script><footer class="ml-case-footer">Дело из серии <a href="../../kto-vret/">«Кто врёт?»</a> · Mystery Logic</footer></body></html>`;
const locked=(item)=>`${head(item)}<body>${brand}<main class="ml-shell locked-case"><section class="ml-card"><p class="ml-kicker">Дело № ${item.number} · полный первый том</p><h1>${escapeHtml(item.title)}</h1><p>Расследование категории «${escapeHtml(item.category||'Логика')}». Материалы и решение не загружаются в публичную страницу до проверки доступа.</p><div class="ml-actions"><a class="ml-button ml-button-primary" href="../../dela/">Вернуться в каталог</a><span class="ml-button ml-button-secondary">Полный том · скоро</span></div></section></main></body></html>`;
export function writeCasePages(siteRoot,cases,editorial){const root=path.join(siteRoot,'delo');fs.rmSync(root,{recursive:true,force:true});ensureDir(root);for(const item of cases){const dir=path.join(root,item.slug);ensureDir(dir);fs.writeFileSync(path.join(dir,'index.html'),editorial||item.access==='free'?playable(item):locked(item));}}
