import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const V2=`${SUPABASE_URL}/functions/v1/ai-moreno-investigator-v2`;
const ALLOWED_ORIGINS=new Set(["https://mysterylogic.com","https://www.mysterylogic.com","https://valera2872.github.io","https://rawcdn.githack.com"]);
const TARGETS=new Set(["boyfriend","mother","older_daughter","younger_daughter","second_floor_witness"]);
const EVIDENCE_ORDER=["scene","interview","canvass","witnessDescription","ballistics","trajectory","weapon","motive","alibi","autopsy"] as const;
type EvidenceId=typeof EVIDENCE_ORDER[number];

function clean(v:unknown,max=900){return typeof v==="string"?v.replace(/[\u0000-\u001f\u007f]/g," ").trim().slice(0,max):""}
function cors(origin:string){return {"access-control-allow-origin":origin||"https://mysterylogic.com","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","vary":"Origin"}}
function qnorm(s:string){return s.toLowerCase().replace(/ё/g,"е").replace(/[.,!?;:()«»\"']/g," ").replace(/\s+/g," ").trim()}
function doneSet(v:unknown){return new Set(Array.isArray(v)?v.map(x=>clean(x,50)).filter(Boolean):[])}
function knownTargets(done:Set<string>){const s=new Set<string>();if(done.has("people")){s.add("boyfriend");s.add("mother");s.add("older_daughter");s.add("younger_daughter")}if(done.has("witnessLocated"))s.add("second_floor_witness");return s}
function explicitTarget(q:string){if(/бойфренд|парн\w*\s+доч/.test(q))return"boyfriend";if(/приемн\w*\s+мат|приёмн\w*\s+мат|\bмать\b|\bматер/.test(q))return"mother";if(/старш\w*\s+доч/.test(q))return"older_daughter";if(/младш\w*\s+доч/.test(q))return"younger_daughter";if(/сосед|жител\w*\s+втор/.test(q))return"second_floor_witness";return""}
function isPresentation(q:string){return /(предъяв|покаж|покажи|показыв|ознаком|сопостав).{0,35}(улик|доказ|материал|результ|показан|баллист|алиби|траектор|оруж|свидетел|описан|вскрыт|осмотр)|(?:баллист|алиби|траектор|оруж|свидетел|описан|вскрыт|осмотр).{0,35}(предъяв|покаж|ознаком)/.test(q)}
function evidenceIds(q:string,done:Set<string>){const ids:EvidenceId[]=[];const add=(id:EvidenceId,re:RegExp)=>{if(done.has(id)&&re.test(q)&&!ids.includes(id))ids.push(id)};if(/все.{0,15}(улик|доказ|материал)/.test(q))return EVIDENCE_ORDER.filter(id=>done.has(id)).slice(0,6) as EvidenceId[];add("alibi",/алиби|сон.{0,12}кресл|кресл.{0,20}(лгал|лгала|оруж)/);add("ballistics",/баллист|калибр|\.38|пул\w*.{0,12}(калибр|оруж)/);add("trajectory",/траектор|точк\w*\s+выстрел|направлен\w*\s+(?:пул|выстр)|дверн\w*\s+проем/);add("witnessDescription",/описан\w*.{0,25}(мужчин|внешност|бойфренд)|внешност\w*.{0,25}свидетел/);add("canvass",/показан\w*.{0,20}(сосед|жител|свидетел)|сосед|бывш\w*\s+жител/);add("weapon",/оруж|пистолет/);add("motive",/угроз|конфликт|отношен/);add("autopsy",/вскрыт|судебно.?мед|ранен|поврежден\w*\s+мозг/);add("scene",/осмотр|сцен|место.{0,12}(преступ|происш)|гильз|взлом/);add("interview",/верс\w*.{0,15}(бойфренд|парн)|показан\w*.{0,15}(бойфренд|парн)/);return ids.slice(0,6)}
function label(id:EvidenceId){return ({scene:"осмотр сцены",interview:"версия бойфренда",canvass:"показания бывшего жильца второго этажа",witnessDescription:"сопоставление описания свидетеля",ballistics:"баллистическое исследование",trajectory:"криминалистическая реконструкция",weapon:"сведения о доступе к оружию",motive:"сведения об угрозах и конфликте",alibi:"проверка версии о сне в кресле",autopsy:"судебно-медицинские материалы"} as Record<EvidenceId,string>)[id]}
function presentationReply(target:string,id:EvidenceId){const reaction="В доступных официальных материалах реакция этого собеседника на такое предъявление не зафиксирована.";const generic:Record<EvidenceId,string>={
 scene:`Вы предъявили материалы осмотра: на месте не нашли оружия и гильз; следов насильственного проникновения в квартиру не зафиксировано. ${reaction}`,
 interview:`Вы предъявили ранее зафиксированную версию бойфренда: он говорил, что спал в кресле, проснулся от двух выстрелов и затем обнаружил Patricia на пожарной лестнице. ${reaction}`,
 canvass:`Вы предъявили показания бывшего жильца второго этажа: после громкого звука он видел Patricia и мужчину, стоявшего над ней; затем мужчина отступил обратно в квартиру и закрыл дверь. ${reaction}`,
 witnessDescription:`Вы предъявили материал позднейшего расследования: описание мужчины, данное независимым свидетелем, сочли соответствующим внешности бойфренда старшей дочери; точные признаки публично не опубликованы. ${reaction}`,
 ballistics:`Вы предъявили результат баллистики: извлечённый из тела Patricia снаряд был совместим с выстрелом из оружия калибра .38. ${reaction}`,
 trajectory:`Вы предъявили криминалистическую реконструкцию: положение входного ранения и нисходящая траектория были совместимы с выстрелом из района дверного проёма квартиры; точный угол публично не опубликован. ${reaction}`,
 weapon:`Вы предъявили сведения позднейшего расследования: у бойфренда старшей дочери было несколько пистолетов, один из которых был совместим с калибром .38. ${reaction}`,
 motive:`Вы предъявили сведения позднейшего расследования об угрожающем поведении бойфренда старшей дочери по отношению к Patricia в недели перед её смертью. ${reaction}`,
 alibi:`Вы предъявили позднейшее признание женщины, защищавшей бойфренда в 1991 году: по её словам, она лгала полиции и большому жюри, а он спрятал оружие в кресле и затем избавился от него. ${reaction}`,
 autopsy:`Вы предъявили судебно-медицинские материалы: одно огнестрельное ранение головы привело к необратимому повреждению мозга; при вскрытии был извлечён снаряд. ${reaction}`
};
 if(target==="boyfriend"&&id==="alibi")return "Вы предъявили позднейшее признание женщины, защищавшей бойфренда в 1991 году: по её словам, она лгала полиции и большому жюри, а он спрятал оружие в кресле и затем избавился от него. Это расходится с его ранее зафиксированной версией о сне в кресле. В доступных официальных материалах реакция самого бойфренда на такое предъявление не зафиксирована.";
 return generic[id];
}
async function forward(req:Request,body:any,headers:Record<string,string>){const auth=req.headers.get("authorization")||"",apikey=req.headers.get("apikey")||"";const r=await fetch(V2,{method:"POST",headers:{authorization:auth,apikey,"content-type":"application/json","origin":req.headers.get("origin")||"https://mysterylogic.com"},body:JSON.stringify(body)});const text=await r.text();return new Response(text,{status:r.status,headers})}

Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin")||"";if(origin&&!ALLOWED_ORIGINS.has(origin))return new Response(JSON.stringify({error:"origin_not_allowed"}),{status:403,headers:{"content-type":"application/json"}});const headers=cors(origin||"https://mysterylogic.com");const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers});if(req.method==="OPTIONS")return new Response("ok",{headers});if(req.method!=="POST")return json({error:"method_not_allowed"},405);let body:any;try{body=await req.json()}catch{return json({error:"invalid_json"},400)};const action=clean(body.action,30),done=doneSet(body.completed);
 if(action==="status")return json({version:3,planner_policy:"compound-v2+source-grounded-confrontation",upstream:"ai-moreno-investigator-v2"});
 if(action==="plan"){const command=clean(body.command,900),q=qnorm(command);if(isPresentation(q)){const known=knownTargets(done),target=explicitTarget(q)||clean(body.focus,40)||clean(body.last_target,40);const ids=evidenceIds(q,done);if(!target||!TARGETS.has(target)||!known.has(target))return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note:"Уточните, кому именно предъявить уже полученный материал."}],mode:"deterministic_confrontation_plan",planner_policy:"compound-v2+source-grounded-confrontation"});if(!ids.length)return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note:"Назовите уже полученный материал, который нужно предъявить собеседнику."}],mode:"deterministic_confrontation_plan",planner_policy:"compound-v2+source-grounded-confrontation"});return json({operations:ids.map(id=>({op:"ask_witness",target,question:`__ML_PRESENT__:${id}`})),mode:"deterministic_confrontation_plan",planner_policy:"compound-v2+source-grounded-confrontation"})}
 }
 if(action==="interrogate"){const question=clean(body.question,700),m=question.match(/^__ML_PRESENT__:(scene|interview|canvass|witnessDescription|ballistics|trajectory|weapon|motive|alibi|autopsy)$/);if(m){const target=clean(body.target,40),id=m[1] as EvidenceId,known=knownTargets(done);if(!TARGETS.has(target)||!known.has(target)||!done.has(id))return json({error:"invalid_confrontation"},400);return json({topic:`present_${id}`,evidence_id:id,evidence_label:label(id),reply:presentationReply(target,id),unlocks:[],mode:target==="boyfriend"&&id==="alibi"?"source_grounded_contradiction":"source_grounded_confrontation",model:"deterministic"})}
 }
 return forward(req,body,headers)
});
