import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const V3=`${SUPABASE_URL}/functions/v1/ai-moreno-investigator-v3`;
const ALLOWED_ORIGINS=new Set(["https://mysterylogic.com","https://www.mysterylogic.com","https://valera2872.github.io","https://rawcdn.githack.com"]);
const TARGETS=new Set(["boyfriend","mother","older_daughter","younger_daughter","second_floor_witness"]);

type MemoryEntry={turn:number;actor_id:string;actor:string;type:"statement"|"confrontation";command:string;title:string;body:string};

function clean(v:unknown,max=1200){return typeof v==="string"?v.replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,max):""}
function qnorm(s:string){return s.toLowerCase().replace(/ё/g,"е").replace(/[.,!?;:()«»\"']/g," ").replace(/\s+/g," ").trim()}
function doneSet(v:unknown){return new Set(Array.isArray(v)?v.map(x=>clean(x,50)).filter(Boolean):[])}
function cors(origin:string){return {"access-control-allow-origin":origin||"https://mysterylogic.com","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store","vary":"Origin"}}
function knownTargets(done:Set<string>){const s=new Set<string>();if(done.has("people")){s.add("boyfriend");s.add("mother");s.add("older_daughter");s.add("younger_daughter")}if(done.has("witnessLocated"))s.add("second_floor_witness");return s}
function explicitTarget(q:string){if(/бойфренд|парн\w*\s+доч/.test(q))return"boyfriend";if(/приемн\w*\s+мат|приёмн\w*\s+мат|\bмать\b|\bматер/.test(q))return"mother";if(/старш\w*\s+доч/.test(q))return"older_daughter";if(/младш\w*\s+доч/.test(q))return"younger_daughter";if(/сосед|жител\w*\s+втор|свидетел\w*\s+втор/.test(q))return"second_floor_witness";return""}
function memoryIntents(q:string){const intents:string[]=[];if(/противореч|расхожд|не сход|говорил\w*\s+иначе|верс\w*.{0,18}не совпад/.test(q))intents.push("contradictions");if(/(что|какие|напомн|вспомн|помн).{0,30}(предъяв|показ|ознаком)|(?:предъяв|показ|ознаком).{0,25}(раньше|уже)/.test(q))intents.push("confrontations");if(/(что|какие|напомн|вспомн|помн).{0,35}(говор|сказ|ответ|показан|верс)|показан\w*.{0,25}(бойфренд|матер|доч|сосед|жител)/.test(q))intents.push("statements");return [...new Set(intents)]}
function memoryEntries(v:unknown){if(!v||typeof v!=="object")return[] as MemoryEntry[];const a=(v as any).entries;if(!Array.isArray(a))return[] as MemoryEntry[];return a.slice(-30).map((e:any)=>({turn:Number(e?.turn)||0,actor_id:clean(e?.actor_id,40),actor:clean(e?.actor,90),type:e?.type==="confrontation"?"confrontation":"statement",command:clean(e?.command,260),title:clean(e?.title,180),body:clean(e?.body,1100)})).filter((e:MemoryEntry)=>e.actor_id&&e.body)}
function targetName(id:string){return ({boyfriend:"бойфренд старшей дочери",mother:"приёмная мать Patricia",older_daughter:"старшая дочь приёмной матери",younger_daughter:"младшая дочь приёмной матери",second_floor_witness:"бывший житель второго этажа"} as Record<string,string>)[id]||id}
function recallStatements(entries:MemoryEntry[],target:string){const rows=entries.filter(e=>e.actor_id===target&&e.type==="statement").slice(-4);if(!rows.length)return`Память дела: отдельных зафиксированных ответов собеседника «${targetName(target)}» в журнале пока нет.`;return`Память дела: зафиксированные ответы собеседника «${targetName(target)}». `+rows.map((e,i)=>`${i+1}) ${e.body}`).join(" ")}
function recallConfrontations(entries:MemoryEntry[],target:string){const rows=entries.filter(e=>e.actor_id===target&&e.type==="confrontation").slice(-4);if(!rows.length)return`Память дела: собеседнику «${targetName(target)}» ещё не предъявляли материалов, зафиксированных в текущем журнале.`;return`Память дела: этому собеседнику уже предъявляли следующие материалы. `+rows.map((e,i)=>`${i+1}) ${e.body}`).join(" ")}
function recallContradictions(entries:MemoryEntry[],target:string,done:Set<string>){const remembered=entries.filter(e=>e.actor_id===target&&/расходит|расхожд|противореч/i.test(e.body)).slice(-3);const rows:string[]=[];for(const e of remembered)if(!rows.includes(e.body))rows.push(e.body);if(target==="boyfriend"&&done.has("interview")&&done.has("alibi")){const fixed="Ранее зафиксированная версия бойфренда о сне в кресле расходится с позднейшим признанием женщины, которая сообщила, что он спрятал оружие в кресле и затем избавился от него.";if(!rows.some(x=>x.includes("сне в кресле")||x.includes("спал в кресле")))rows.push(fixed)}if(!rows.length)return`Память дела: объективных расхождений между уже полученными материалами по собеседнику «${targetName(target)}» пока не зафиксировано.`;return`Память дела: объективно зафиксированные расхождения по собеседнику «${targetName(target)}». `+rows.map((x,i)=>`${i+1}) ${x}`).join(" ")}
function recall(kind:string,entries:MemoryEntry[],target:string,done:Set<string>){return kind==="statements"?recallStatements(entries,target):kind==="confrontations"?recallConfrontations(entries,target):recallContradictions(entries,target,done)}
async function forward(req:Request,body:any,headers:Record<string,string>){const auth=req.headers.get("authorization")||"",apikey=req.headers.get("apikey")||"";const r=await fetch(V3,{method:"POST",headers:{authorization:auth,apikey,"content-type":"application/json","origin":req.headers.get("origin")||"https://mysterylogic.com"},body:JSON.stringify(body)});const text=await r.text();return new Response(text,{status:r.status,headers})}

Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin")||"";if(origin&&!ALLOWED_ORIGINS.has(origin))return new Response(JSON.stringify({error:"origin_not_allowed"}),{status:403,headers:{"content-type":"application/json"}});const headers=cors(origin||"https://mysterylogic.com");const json=(x:unknown,status=200)=>new Response(JSON.stringify(x),{status,headers});if(req.method==="OPTIONS")return new Response("ok",{headers});if(req.method!=="POST")return json({error:"method_not_allowed"},405);let body:any;try{body=await req.json()}catch{return json({error:"invalid_json"},400)};const action=clean(body.action,30),done=doneSet(body.completed),entries=memoryEntries(body.memory);
 if(action==="status")return json({version:4,planner_policy:"compound-v2+source-grounded-confrontation+deterministic-memory",upstream:"ai-moreno-investigator-v3"});
 if(action==="plan"){const q=qnorm(clean(body.command,900)),intents=memoryIntents(q);if(intents.length){const known=knownTargets(done),focus=clean(body.focus,40);let lookup=explicitTarget(q)||focus||clean(body.last_target,40);if(!lookup&&intents.includes("contradictions")&&done.has("people")&&done.has("interview")&&done.has("alibi"))lookup="boyfriend";if(!lookup||!TARGETS.has(lookup)||!known.has(lookup))return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note:"Уточните, чьи уже зафиксированные показания или предъявления нужно поднять из памяти дела."}],mode:"deterministic_memory_plan",planner_policy:"compound-v2+source-grounded-confrontation+deterministic-memory"});if(!focus){const note=intents.slice(0,3).map(kind=>recall(kind,entries,lookup,done)).join(" ");return json({operations:[{op:"clarify",target:null,question:null,hypothesis:null,note}],mode:"deterministic_memory_plan",planner_policy:"compound-v2+source-grounded-confrontation+deterministic-memory"})}const executionTarget=known.has(focus)?focus:lookup;return json({operations:intents.slice(0,3).map(kind=>({op:"ask_witness",target:executionTarget,question:`__ML_MEMORY__:${kind}:${lookup}`})),mode:"deterministic_memory_plan",planner_policy:"compound-v2+source-grounded-confrontation+deterministic-memory"})}}
 if(action==="interrogate"){const question=clean(body.question,180),m=question.match(/^__ML_MEMORY__:(statements|confrontations|contradictions)(?::(boyfriend|mother|older_daughter|younger_daughter|second_floor_witness))?$/);if(m){const executionTarget=clean(body.target,40),lookup=m[2]||executionTarget,known=knownTargets(done);if(!TARGETS.has(executionTarget)||!known.has(executionTarget)||!TARGETS.has(lookup)||!known.has(lookup))return json({error:"invalid_memory_target"},400);const kind=m[1],reply=recall(kind,entries,lookup,done);return json({topic:`memory_${kind}`,reply,unlocks:[],mode:"memory_recall",model:"deterministic",memory_kind:kind,memory_target:lookup})}}
 return forward(req,body,headers)
});
