-- Review moderation metadata and anonymous first-party funnel analytics.
-- The moderation access credential itself is provisioned out-of-band and is never committed.

alter table public.case_reviews
  add column if not exists moderation_note text,
  add column if not exists moderated_at timestamptz;

create table if not exists public.review_moderation_access (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  label text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);

alter table public.review_moderation_access enable row level security;
revoke all on public.review_moderation_access from anon, authenticated;
grant select, insert, update on public.review_moderation_access to service_role;

create table if not exists public.site_funnel_events (
  id bigint generated by default as identity primary key,
  visitor_key_hash text not null,
  session_key_hash text not null,
  event_name text not null,
  page_path text not null,
  page_group text not null,
  target text,
  referrer_host text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint site_funnel_event_name_check check (event_name ~ '^[a-z0-9_]{3,64}$'),
  constraint site_funnel_path_check check (char_length(page_path) between 1 and 500),
  constraint site_funnel_group_check check (page_group ~ '^[a-z0-9_-]{2,64}$')
);

alter table public.site_funnel_events enable row level security;
revoke all on public.site_funnel_events from anon, authenticated;
grant select, insert on public.site_funnel_events to service_role;

create index if not exists site_funnel_events_created_idx
  on public.site_funnel_events(created_at desc);
create index if not exists site_funnel_events_event_idx
  on public.site_funnel_events(event_name, created_at desc);
create index if not exists site_funnel_events_page_idx
  on public.site_funnel_events(page_group, event_name, created_at desc);
create index if not exists site_funnel_events_session_idx
  on public.site_funnel_events(session_key_hash, created_at);
