alter table public.payment_orders
  add column if not exists offer_version text,
  add column if not exists offer_accepted_at timestamptz,
  add column if not exists privacy_version text,
  add column if not exists privacy_acknowledged_at timestamptz;

create table if not exists public.paid_access_audit (
  id bigint generated by default as identity primary key,
  entitlement_id uuid not null references public.access_entitlements(id) on delete cascade,
  order_id uuid references public.payment_orders(id) on delete set null,
  product_id text not null default 'volume1',
  case_id text not null,
  event_type text not null default 'payload_delivered',
  payload_version integer,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint paid_access_audit_event_type_check check (event_type in ('payload_delivered'))
);

create index if not exists paid_access_audit_entitlement_idx
  on public.paid_access_audit(entitlement_id, occurred_at desc);

create index if not exists paid_access_audit_order_idx
  on public.paid_access_audit(order_id, occurred_at desc)
  where order_id is not null;

create index if not exists paid_access_audit_case_idx
  on public.paid_access_audit(case_id, occurred_at desc);

alter table public.paid_access_audit enable row level security;

comment on table public.paid_access_audit is
  'Server-side evidence of successful delivery of paid case payloads. Service-role only; no public policies.';
